paths:
  genomes: "../data/genomes/"
  models: "../data/modelseedpy/"
  modelseed: "../data/modelseed/"
  retropath: "../data/retropath/"

retropath:
  files:
    ec_numbers: "ec_numbers_all.csv"
    rules: "ec_numbers_all_rules.csv"
    sink: "ec_numbers_all_sink.csv"
