paths:
  figures: "../data/figures/"
  genomes: "../data/genomes/"
  metanetx: "../data/metanetx/"
  models: "../data/gem/"
  modelseed: "../data/modelseed/"
  retropath: "../data/retropath/"
  retrorules: "../data/retrorules/retrorules_rr01_rp2_flat_forward.csv"

retropath:
  files:
    ec_numbers: "ec_numbers.csv"
    rules: "rules.csv"
    sink: "sink.csv"
    sources: "metabolitos_producibles.csv"
  params:
    dmax: 16
    dmin: 6
    max_steps: 10
    topx: 100
    mwmax_source: 1000

figures:
  template: "plotly_white"
