paths:
  genomes: "../data/genomes/"
  metanetx: "../data/metanetx/"
  models: "../data/gem/"
  modelseed: "../data/modelseed/"
  retropath: "../data/retropath/"
  retrorules: "../data/retrorules/retrorules_rr01_rp2_flat_forward.csv"

retropath:
  files:
    ec_numbers: "ec_numbers.csv"
    rules: "rules.csv"
    sink: "sink.csv"
