paths:
  genomes: "../data/genomes/"
  metanetx: "../data/metanetx/"
  models: "../data/modelseedpy/"
  modelseed: "../data/modelseed/"
  retropath: "../data/retropath/"
  retrorules: "../data/retrorules/retrorules_rr01_rp2_flat_forward.csv"

retropath:
  files:
    ec_numbers: "ec_numbers_all.csv"
    rules: "ec_numbers_all_rules.csv"
    sink: "ec_numbers_all_sink.csv"
