import numpy as np
import pandas as pd

import plotly
import plotly.express as px


def plot_abundances_depth(
    taxonomy_df: pd.DataFrame,
    config: dict
) -> plotly.graph_objects.Figure:
    """
    Plot the abundances of each species at different depths.

    Parameters
    ----------
    taxonomy_df : pandas.DataFrame
        Dataframe generated by MICOMPreloader containing both the taxonomy and
        the abundances of each species at different depths.
    config : dict
        The configuration dictionary.

    Returns
    -------
    fig : plotly.graph_objects.Figure
        The generated figure.

    Examples
    --------
    None

    """

    taxonomy_df["Code"] = taxonomy_df["file"]\
        .apply(lambda row: row.split("/")[-1].split("_")[0])

    taxonomy_df["Depth"] = taxonomy_df["sample_id"]\
        .str.split("-").str[1].astype(int, errors="ignore")

    taxonomy_df["log_abundance"] = np.log1p(taxonomy_df["abundance"])

    # Convert to long
    taxonomy_matrix = taxonomy_df.pivot(
        columns="Code",
        index="Depth",
        values="log_abundance"
    )

    fig = px.imshow(
        img=taxonomy_matrix,
        x=taxonomy_matrix.columns,
        y=taxonomy_matrix.index,
        labels=dict(
            x="Species",
            y="Depth",
            color="log(Abundance)"
        ),
        aspect="auto",
        template=config["figures"]["template"]
    )

    return fig


def plot_minimal_medium(
    min_medium: pd.DataFrame,
    top_n: dict,
    config: dict
) -> plotly.graph_objects.Figure:
    """
    Plot the computed minimal medium.

    Parameters
    ----------
    min_medium : pandas.DataFrame
        Minimal medium computed for a given community.
    top_n : int
        Top fluxes to show.
    config : dict
        The configuration dictionary.

    Returns
    -------
    fig : plotly.graph_objects.Figure
        The generated figure.

    Examples
    --------
    None

    """

    fig = px.bar(
        data_frame=min_medium\
            .sort_values("flux", ascending=False)\
            .head(top_n)\
            .rename(columns={"reaction": "Reaction", "flux": "Flux"}),
        x="Reaction",
        y="Flux",
        color="Flux",
        template=config["figures"]["template"]
    )
    fig.update_coloraxes(showscale=False)

    return fig
